title: PETS 2022 Workshop on Multiparty and Interdependent Privacy
#"My privacy, your privacy, our privacy: when online privacy is multiparty and interdependent"
description: July 11, 2022 in Sydney and Online

