title: PETS 2022 Workshop on Multiparty and Interdependent Privacy
#"My privacy, your privacy, our privacy: when online privacy is multiparty and interdependent"
description: Date: July 11, 2022. Place: Sydney and Online

